import type { Stroke } from './strokeMath';

// Vertical breathing room (em units) between the base glyph and a mark.
const MARK_GAP = 30;
// Horn sits at the upper-right of the base, with its bottom near the base's middle.
const HORN_RIGHT_INSET = 20;
const HORN_TOP_DROP = 80;

// Mark position relative to the base it's stacked onto. The composer reads
// these to figure out where to put each accent — including stacked marks like
// ổ (o + circumflex + hook).
export type MarkPosition = 'above' | 'below' | 'upper-right';

const MARK_POSITIONS: Readonly<Record<number, MarkPosition>> = {
  0x00b4: 'above', // ´ acute
  0x0060: 'above', // ` grave
  0x02c6: 'above', // ˆ circumflex
  0x00a8: 'above', // ¨ diaeresis
  0x02dc: 'above', // ˜ small tilde
  0x02d8: 'above', // ˘ breve
  0xe000: 'above', //    hook above
  0xe001: 'below', //    dot below
  0xe002: 'upper-right', // horn
};

type ComposeRecipe = {
  readonly base: number;
  // Applied in order. Later marks stack above the earlier accumulated glyph,
  // so 'ổ' = o → +circumflex → +hook lands the hook above the circumflex.
  readonly marks: readonly number[];
};

// Generated by combineMarks. Keyed by Unicode code point for the composed form.
const RECIPES: Readonly<Record<number, ComposeRecipe>> = (() => {
  const ACUTE = 0x00b4;
  const GRAVE = 0x0060;
  const CIRC = 0x02c6;
  const DIA = 0x00a8;
  const TILDE = 0x02dc;
  const BREVE = 0x02d8;
  const HOOK = 0xe000;
  const DOT = 0xe001;
  const HORN = 0xe002;

  return {
    // a-family
    0x00e0: { base: 0x61, marks: [GRAVE] },                  // à
    0x00e1: { base: 0x61, marks: [ACUTE] },                  // á
    0x00e2: { base: 0x61, marks: [CIRC] },                   // â
    0x00e3: { base: 0x61, marks: [TILDE] },                  // ã
    0x00e4: { base: 0x61, marks: [DIA] },                    // ä
    0x1ea1: { base: 0x61, marks: [DOT] },                    // ạ
    0x1ea3: { base: 0x61, marks: [HOOK] },                   // ả
    0x0103: { base: 0x61, marks: [BREVE] },                  // ă
    0x1eaf: { base: 0x0103, marks: [ACUTE] },                // ắ
    0x1eb1: { base: 0x0103, marks: [GRAVE] },                // ằ
    0x1eb3: { base: 0x0103, marks: [HOOK] },                 // ẳ
    0x1eb5: { base: 0x0103, marks: [TILDE] },                // ẵ
    0x1eb7: { base: 0x0103, marks: [DOT] },                  // ặ
    0x1ea5: { base: 0x00e2, marks: [ACUTE] },                // ấ
    0x1ea7: { base: 0x00e2, marks: [GRAVE] },                // ầ
    0x1ea9: { base: 0x00e2, marks: [HOOK] },                 // ẩ
    0x1eab: { base: 0x00e2, marks: [TILDE] },                // ẫ
    0x1ead: { base: 0x00e2, marks: [DOT] },                  // ậ

    // e-family
    0x00e8: { base: 0x65, marks: [GRAVE] },                  // è
    0x00e9: { base: 0x65, marks: [ACUTE] },                  // é
    0x00ea: { base: 0x65, marks: [CIRC] },                   // ê
    0x00eb: { base: 0x65, marks: [DIA] },                    // ë
    0x1eb9: { base: 0x65, marks: [DOT] },                    // ẹ
    0x1ebb: { base: 0x65, marks: [HOOK] },                   // ẻ
    0x1ebd: { base: 0x65, marks: [TILDE] },                  // ẽ
    0x1ebf: { base: 0x00ea, marks: [ACUTE] },                // ế
    0x1ec1: { base: 0x00ea, marks: [GRAVE] },                // ề
    0x1ec3: { base: 0x00ea, marks: [HOOK] },                 // ể
    0x1ec5: { base: 0x00ea, marks: [TILDE] },                // ễ
    0x1ec7: { base: 0x00ea, marks: [DOT] },                  // ệ

    // i-family
    0x00ec: { base: 0x69, marks: [GRAVE] },                  // ì
    0x00ed: { base: 0x69, marks: [ACUTE] },                  // í
    0x00ee: { base: 0x69, marks: [CIRC] },                   // î
    0x00ef: { base: 0x69, marks: [DIA] },                    // ï
    0x0129: { base: 0x69, marks: [TILDE] },                  // ĩ
    0x1ec9: { base: 0x69, marks: [HOOK] },                   // ỉ
    0x1ecb: { base: 0x69, marks: [DOT] },                    // ị

    // o-family
    0x00f2: { base: 0x6f, marks: [GRAVE] },                  // ò
    0x00f3: { base: 0x6f, marks: [ACUTE] },                  // ó
    0x00f4: { base: 0x6f, marks: [CIRC] },                   // ô
    0x00f5: { base: 0x6f, marks: [TILDE] },                  // õ
    0x00f6: { base: 0x6f, marks: [DIA] },                    // ö
    0x1ecd: { base: 0x6f, marks: [DOT] },                    // ọ
    0x1ecf: { base: 0x6f, marks: [HOOK] },                   // ỏ
    0x1ed1: { base: 0x00f4, marks: [ACUTE] },                // ố
    0x1ed3: { base: 0x00f4, marks: [GRAVE] },                // ồ
    0x1ed5: { base: 0x00f4, marks: [HOOK] },                 // ổ
    0x1ed7: { base: 0x00f4, marks: [TILDE] },                // ỗ
    0x1ed9: { base: 0x00f4, marks: [DOT] },                  // ộ
    0x01a1: { base: 0x6f, marks: [HORN] },                   // ơ
    0x1edb: { base: 0x01a1, marks: [ACUTE] },                // ớ
    0x1edd: { base: 0x01a1, marks: [GRAVE] },                // ờ
    0x1edf: { base: 0x01a1, marks: [HOOK] },                 // ở
    0x1ee1: { base: 0x01a1, marks: [TILDE] },                // ỡ
    0x1ee3: { base: 0x01a1, marks: [DOT] },                  // ợ

    // u-family
    0x00f9: { base: 0x75, marks: [GRAVE] },                  // ù
    0x00fa: { base: 0x75, marks: [ACUTE] },                  // ú
    0x00fb: { base: 0x75, marks: [CIRC] },                   // û
    0x00fc: { base: 0x75, marks: [DIA] },                    // ü
    0x0169: { base: 0x75, marks: [TILDE] },                  // ũ
    0x1ee5: { base: 0x75, marks: [DOT] },                    // ụ
    0x1ee7: { base: 0x75, marks: [HOOK] },                   // ủ
    0x01b0: { base: 0x75, marks: [HORN] },                   // ư
    0x1ee9: { base: 0x01b0, marks: [ACUTE] },                // ứ
    0x1eeb: { base: 0x01b0, marks: [GRAVE] },                // ừ
    0x1eed: { base: 0x01b0, marks: [HOOK] },                 // ử
    0x1eef: { base: 0x01b0, marks: [TILDE] },                // ữ
    0x1ef1: { base: 0x01b0, marks: [DOT] },                  // ự

    // y-family
    0x00fd: { base: 0x79, marks: [ACUTE] },                  // ý
    0x00ff: { base: 0x79, marks: [DIA] },                    // ÿ
    0x1ef3: { base: 0x79, marks: [GRAVE] },                  // ỳ
    0x1ef5: { base: 0x79, marks: [DOT] },                    // ỵ
    0x1ef7: { base: 0x79, marks: [HOOK] },                   // ỷ
    0x1ef9: { base: 0x79, marks: [TILDE] },                  // ỹ

    // n-tilde
    0x00f1: { base: 0x6e, marks: [TILDE] },                  // ñ

    // ── uppercase variants ──────────────────────────────────────────────

    // A-family
    0x00c0: { base: 0x41, marks: [GRAVE] },                  // À
    0x00c1: { base: 0x41, marks: [ACUTE] },                  // Á
    0x00c2: { base: 0x41, marks: [CIRC] },                   // Â
    0x00c3: { base: 0x41, marks: [TILDE] },                  // Ã
    0x00c4: { base: 0x41, marks: [DIA] },                    // Ä
    0x1ea0: { base: 0x41, marks: [DOT] },                    // Ạ
    0x1ea2: { base: 0x41, marks: [HOOK] },                   // Ả
    0x0102: { base: 0x41, marks: [BREVE] },                  // Ă
    0x1eae: { base: 0x0102, marks: [ACUTE] },                // Ắ
    0x1eb0: { base: 0x0102, marks: [GRAVE] },                // Ằ
    0x1eb2: { base: 0x0102, marks: [HOOK] },                 // Ẳ
    0x1eb4: { base: 0x0102, marks: [TILDE] },                // Ẵ
    0x1eb6: { base: 0x0102, marks: [DOT] },                  // Ặ
    0x1ea4: { base: 0x00c2, marks: [ACUTE] },                // Ấ
    0x1ea6: { base: 0x00c2, marks: [GRAVE] },                // Ầ
    0x1ea8: { base: 0x00c2, marks: [HOOK] },                 // Ẩ
    0x1eaa: { base: 0x00c2, marks: [TILDE] },                // Ẫ
    0x1eac: { base: 0x00c2, marks: [DOT] },                  // Ậ

    // E-family
    0x00c8: { base: 0x45, marks: [GRAVE] },                  // È
    0x00c9: { base: 0x45, marks: [ACUTE] },                  // É
    0x00ca: { base: 0x45, marks: [CIRC] },                   // Ê
    0x00cb: { base: 0x45, marks: [DIA] },                    // Ë
    0x1eb8: { base: 0x45, marks: [DOT] },                    // Ẹ
    0x1eba: { base: 0x45, marks: [HOOK] },                   // Ẻ
    0x1ebc: { base: 0x45, marks: [TILDE] },                  // Ẽ
    0x1ebe: { base: 0x00ca, marks: [ACUTE] },                // Ế
    0x1ec0: { base: 0x00ca, marks: [GRAVE] },                // Ề
    0x1ec2: { base: 0x00ca, marks: [HOOK] },                 // Ể
    0x1ec4: { base: 0x00ca, marks: [TILDE] },                // Ễ
    0x1ec6: { base: 0x00ca, marks: [DOT] },                  // Ệ

    // I-family (capital I has no tittle so the dropTittle heuristic is a no-op)
    0x00cc: { base: 0x49, marks: [GRAVE] },                  // Ì
    0x00cd: { base: 0x49, marks: [ACUTE] },                  // Í
    0x00ce: { base: 0x49, marks: [CIRC] },                   // Î
    0x00cf: { base: 0x49, marks: [DIA] },                    // Ï
    0x0128: { base: 0x49, marks: [TILDE] },                  // Ĩ
    0x1ec8: { base: 0x49, marks: [HOOK] },                   // Ỉ
    0x1eca: { base: 0x49, marks: [DOT] },                    // Ị

    // O-family
    0x00d2: { base: 0x4f, marks: [GRAVE] },                  // Ò
    0x00d3: { base: 0x4f, marks: [ACUTE] },                  // Ó
    0x00d4: { base: 0x4f, marks: [CIRC] },                   // Ô
    0x00d5: { base: 0x4f, marks: [TILDE] },                  // Õ
    0x00d6: { base: 0x4f, marks: [DIA] },                    // Ö
    0x1ecc: { base: 0x4f, marks: [DOT] },                    // Ọ
    0x1ece: { base: 0x4f, marks: [HOOK] },                   // Ỏ
    0x1ed0: { base: 0x00d4, marks: [ACUTE] },                // Ố
    0x1ed2: { base: 0x00d4, marks: [GRAVE] },                // Ồ
    0x1ed4: { base: 0x00d4, marks: [HOOK] },                 // Ổ
    0x1ed6: { base: 0x00d4, marks: [TILDE] },                // Ỗ
    0x1ed8: { base: 0x00d4, marks: [DOT] },                  // Ộ
    0x01a0: { base: 0x4f, marks: [HORN] },                   // Ơ
    0x1eda: { base: 0x01a0, marks: [ACUTE] },                // Ớ
    0x1edc: { base: 0x01a0, marks: [GRAVE] },                // Ờ
    0x1ede: { base: 0x01a0, marks: [HOOK] },                 // Ở
    0x1ee0: { base: 0x01a0, marks: [TILDE] },                // Ỡ
    0x1ee2: { base: 0x01a0, marks: [DOT] },                  // Ợ

    // U-family
    0x00d9: { base: 0x55, marks: [GRAVE] },                  // Ù
    0x00da: { base: 0x55, marks: [ACUTE] },                  // Ú
    0x00db: { base: 0x55, marks: [CIRC] },                   // Û
    0x00dc: { base: 0x55, marks: [DIA] },                    // Ü
    0x0168: { base: 0x55, marks: [TILDE] },                  // Ũ
    0x1ee4: { base: 0x55, marks: [DOT] },                    // Ụ
    0x1ee6: { base: 0x55, marks: [HOOK] },                   // Ủ
    0x01af: { base: 0x55, marks: [HORN] },                   // Ư
    0x1ee8: { base: 0x01af, marks: [ACUTE] },                // Ứ
    0x1eea: { base: 0x01af, marks: [GRAVE] },                // Ừ
    0x1eec: { base: 0x01af, marks: [HOOK] },                 // Ử
    0x1eee: { base: 0x01af, marks: [TILDE] },                // Ữ
    0x1ef0: { base: 0x01af, marks: [DOT] },                  // Ự

    // Y-family
    0x00dd: { base: 0x59, marks: [ACUTE] },                  // Ý
    0x0178: { base: 0x59, marks: [DIA] },                    // Ÿ
    0x1ef2: { base: 0x59, marks: [GRAVE] },                  // Ỳ
    0x1ef4: { base: 0x59, marks: [DOT] },                    // Ỵ
    0x1ef6: { base: 0x59, marks: [HOOK] },                   // Ỷ
    0x1ef8: { base: 0x59, marks: [TILDE] },                  // Ỹ

    // N-tilde
    0x00d1: { base: 0x4e, marks: [TILDE] },                  // Ñ
  };
})();

export const COMPOSITION_RECIPES = RECIPES;

// Stable, dependency-aware ordering: every recipe appears after the recipe
// for its base (if any). composeAll relies on this so chained bases like
// ô → ổ resolve in one pass.
export const COMPOSABLE_TARGETS: readonly number[] = (() => {
  const all = Object.keys(RECIPES).map((k) => Number(k));
  const recipeMap = RECIPES;
  const visited = new Set<number>();
  const out: number[] = [];
  const visit = (cp: number): void => {
    if (visited.has(cp)) return;
    const r = recipeMap[cp];
    if (r && recipeMap[r.base]) visit(r.base);
    visited.add(cp);
    if (r) out.push(cp);
  };
  for (const cp of all) visit(cp);
  return out;
})();

export type StrokeLookup = (codePoint: number) => Stroke[] | null | undefined;

export type ComposeResult =
  | { ok: true; strokes: Stroke[] }
  | { ok: false; missing: number[] };

// Returns composed strokes for `target`, or the list of code points still
// missing from `lookup`. `lookup` is expected to return both user-drawn and
// previously-composed strokes — composeAll passes a working map for that.
export function composeGlyph(target: number, lookup: StrokeLookup): ComposeResult {
  const recipe = RECIPES[target];
  if (!recipe) return { ok: false, missing: [] };

  const missing: number[] = [];
  const baseStrokes = lookup(recipe.base);
  if (!baseStrokes || baseStrokes.length === 0) missing.push(recipe.base);
  for (const mark of recipe.marks) {
    const ms = lookup(mark);
    if (!ms || ms.length === 0) missing.push(mark);
  }
  if (missing.length > 0) return { ok: false, missing };

  const hasAboveMark = recipe.marks.some((m) => MARK_POSITIONS[m] === 'above');
  const isDottedBase = recipe.base === 0x69 || recipe.base === 0x6a;
  const initialBase =
    isDottedBase && hasAboveMark ? stripTittle(baseStrokes!) : cloneStrokes(baseStrokes!);

  let accumulated: Stroke[] = initialBase;
  for (const markCp of recipe.marks) {
    const markStrokes = lookup(markCp)!;
    const position = MARK_POSITIONS[markCp] ?? 'above';
    const placed = placeMark(markStrokes, accumulated, position);
    accumulated = [...accumulated, ...placed];
  }
  return { ok: true, strokes: accumulated };
}

export type ComposeAllOptions = {
  // When true, source='composed' glyphs are overwritten on every pass so a
  // tweak to a primitive flows through to every dependent. drawnSource entries
  // are always left alone.
  readonly drawnCodePoints: ReadonlySet<number>;
};

// Walks COMPOSABLE_TARGETS in dependency order, composing every target whose
// dependencies resolve. Returns just the newly-composed glyphs.
export function composeAll(
  initial: ReadonlyMap<number, Stroke[]>,
  options: ComposeAllOptions,
): Map<number, Stroke[]> {
  const working = new Map<number, Stroke[]>(initial);
  const produced = new Map<number, Stroke[]>();
  const lookup: StrokeLookup = (cp) => working.get(cp) ?? null;

  for (const target of COMPOSABLE_TARGETS) {
    if (options.drawnCodePoints.has(target)) continue;
    const result = composeGlyph(target, lookup);
    if (!result.ok) continue;
    working.set(target, result.strokes);
    produced.set(target, result.strokes);
  }
  return produced;
}

type BBox = { minX: number; minY: number; maxX: number; maxY: number };

export function strokesBoundingBox(strokes: readonly Stroke[]): BBox | null {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  let any = false;
  for (const s of strokes) {
    for (const p of s) {
      any = true;
      if (p.x < minX) minX = p.x;
      if (p.x > maxX) maxX = p.x;
      if (p.y < minY) minY = p.y;
      if (p.y > maxY) maxY = p.y;
    }
  }
  return any ? { minX, minY, maxX, maxY } : null;
}

function cloneStrokes(strokes: readonly Stroke[]): Stroke[] {
  return strokes.map((s) => s.map((p) => ({ ...p })));
}

function translateStrokes(strokes: readonly Stroke[], dx: number, dy: number): Stroke[] {
  return strokes.map((s) =>
    s.map((p) => ({
      x: p.x + dx,
      y: p.y + dy,
      pressure: p.pressure,
      ...(p.isAnchor ? { isAnchor: true as const } : {}),
    })),
  );
}

function placeMark(
  mark: readonly Stroke[],
  accumulated: readonly Stroke[],
  position: MarkPosition,
): Stroke[] {
  const aBox = strokesBoundingBox(mark);
  const bBox = strokesBoundingBox(accumulated);
  if (!aBox || !bBox) return cloneStrokes(mark);

  if (position === 'above') {
    const aCenterX = (aBox.minX + aBox.maxX) / 2;
    const bCenterX = (bBox.minX + bBox.maxX) / 2;
    return translateStrokes(mark, bCenterX - aCenterX, bBox.minY - MARK_GAP - aBox.maxY);
  }

  if (position === 'below') {
    const aCenterX = (aBox.minX + aBox.maxX) / 2;
    const bCenterX = (bBox.minX + bBox.maxX) / 2;
    return translateStrokes(mark, bCenterX - aCenterX, bBox.maxY + MARK_GAP - aBox.minY);
  }

  // 'upper-right' — horn anchors to the base's upper-right corner.
  const targetRight = bBox.maxX + HORN_RIGHT_INSET;
  const targetTop = bBox.minY + HORN_TOP_DROP;
  return translateStrokes(mark, targetRight - aBox.minX, targetTop - aBox.minY);
}

// i/j tittle removal: the dot is the shortest stroke AND sits fully above the
// rest (its lowest point is still above the rest's highest point). The
// "fully above" check stops us nuking a t-bar or an f-bar by accident.
function stripTittle(strokes: readonly Stroke[]): Stroke[] {
  if (strokes.length < 2) return cloneStrokes(strokes);
  let smallestIdx = 0;
  let smallestLen = strokeLength(strokes[0]!);
  for (let i = 1; i < strokes.length; i++) {
    const len = strokeLength(strokes[i]!);
    if (len < smallestLen) {
      smallestIdx = i;
      smallestLen = len;
    }
  }
  const smallest = strokes[smallestIdx]!;
  const rest = strokes.filter((_, i) => i !== smallestIdx);
  const smallestBox = strokesBoundingBox([smallest]);
  const restBox = strokesBoundingBox(rest);
  if (!smallestBox || !restBox) return cloneStrokes(strokes);
  if (smallestBox.maxY >= restBox.minY) return cloneStrokes(strokes);
  return rest.map((s) => s.map((p) => ({ ...p })));
}

function strokeLength(stroke: Stroke): number {
  if (stroke.length < 2) return 0;
  let d = 0;
  for (let i = 1; i < stroke.length; i++) {
    const a = stroke[i - 1]!;
    const b = stroke[i]!;
    d += Math.hypot(b.x - a.x, b.y - a.y);
  }
  return d;
}
